<img src="./img/DC_Gray _Logo.png">

<center><h2> Module 3 Project</h2></center>
<center><h2> Hypothesis Testing</h2></center>

**Authors:** Marissa Eppes, Yijing Li

#### Business Problem
How do entrepreneurs of various socioeconomic status hire and pay employees?

#### Analysis

In [11]:
import pandas as pd
import data_cleaning as dc
import numpy as np
import warnings
warnings.filterwarnings('ignore')
%load_ext autoreload
%autoreload 2
dirty_data = pd.read_csv('./data/dirty_data.csv')
data = dc.full_clean()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [12]:
data

,emp,empszfi,empszfi_ttl,eth_group,eth_group_ttl,firmpdemp,geotype,naics2012,naics2012_ttl,payann,...,rcppdemp,rcpszfi,rcpszfi_ttl,sex,sex_ttl,vet_group,vet_group_ttl,payann_log,emp_log,rcppdemp_log
0,6973459,641,Firms with 20 to 49 employees,1,All firms,231413,1,00,Total for all sectors,291824041,...,1385683572,1,All firms,3,Male-owned,1,All firms,19.491662,15.757622,21.049459
1,4663039,642,Firms with 50 to 99 employees,1,All firms,68449,1,00,Total for all sectors,208586006,...,1107167693,1,All firms,3,Male-owned,1,All firms,19.155862,15.355178,20.825071
2,4689659,651,Firms with 100 to 249 employees,1,All firms,31606,1,00,Total for all sectors,221101882,...,1267764684,1,All firms,3,Male-owned,1,All firms,19.214134,15.360870,20.960521
3,2725228,652,Firms with 250 to 499 employees,1,All firms,7988,1,00,Total for all sectors,133578039,...,751005091,1,All firms,3,Male-owned,1,All firms,18.710196,14.818063,20.436923
4,8775515,657,Firms with 500 employees or more,1,All firms,5205,1,00,Total for all sectors,349587211,...,1942901019,1,All firms,3,Male-owned,1,All firms,19.672264,15.987476,21.387448
5,6696450,1,All firms,1,All firms,774405,1,00,Total for all sectors,205449017,...,991077570,1,All firms,4,Equally male-/female-owned,1,All firms,19.140708,15.717088,20.714303
6,316697,1,All firms,1,All firms,65308,1,00,Total for all sectors,7657545,...,37553551,1,All firms,4,Equally male-/female-owned,1,All firms,15.851202,12.665701,17.441278
7,607482,1,All firms,1,All firms,102522,1,00,Total for all sectors,13953198,...,62881701,1,All firms,4,Equally male-/female-owned,1,All firms,16.451219,13.317078,17.956766
8,518691,1,All firms,1,All firms,71833,1,00,Total for all sectors,12559093,...,57158086,1,All firms,4,Equally male-/female-owned,1,All firms,16.345956,13.159064,17.861331
9,1275486,1,All firms,1,All firms,174833,1,00,Total for all sectors,35596377,...,160926487,1,All firms,4,Equally male-/female-owned,1,All firms,17.387754,14.058838,18.896458
10,3144473,1,All firms,1,All firms,342409,1,00,Total for all sectors,107569484,...,504376870,1,All firms,4,Equally male-/female-owned,1,All firms,18.493648,14.961157,20.038834
11,833622,1,All firms,1,All firms,17501,1,00,Total for all sectors,28113319,...,168180875,1,All firms,4,Equally male-/female-owned,1,All firms,17.151754,13.633535,18.940551
12,19983,1,All firms,1,All firms,3152,1,00,Total for all sectors,607630,...,2497718,1,All firms,4,Equally male-/female-owned,2,Veteran-owned,13.317321,9.902637,14.730888
13,821999,1,All firms,1,All firms,115198,1,00,Total for all sectors,24656681,...,118300580,1,All firms,4,Equally male-/female-owned,3,Equally veteran-/nonveteran-owned,17.020558,13.619494,18.588739
14,5854468,1,All firms,1,All firms,656055,1,00,Total for all sectors,180184707,...,870279272,1,All firms,4,Equally male-/female-owned,4,Nonveteran-owned,19.009493,15.582716,20.584325
15,315912,1,All firms,20,Hispanic,34394,1,00,Total for all sectors,7429183,...,34292021,1,All firms,4,Equally male-/female-owned,1,All firms,15.820926,12.663219,17.350423
16,254447,1,All firms,28,Equally Hispanic/non-Hispanic,33427,1,00,Total for all sectors,7390416,...,30228622,1,All firms,4,Equally male-/female-owned,1,All firms,15.815695,12.446848,17.224300
17,6126091,1,All firms,29,Non-Hispanic,706584,1,00,Total for all sectors,190629419,...,926556926,1,All firms,4,Equally male-/female-owned,1,All firms,19.065842,15.628067,20.646986
18,19177,1,All firms,1,All firms,14085,1,00,Total for all sectors,421318,...,69116,510,"Firms with sales/receipts of less than $10,000",4,Equally male-/female-owned,1,All firms,12.951143,9.861467,11.143542
19,63120,1,All firms,1,All firms,54306,1,00,Total for all sectors,665691,...,1595109,520,"Firms with sales/receipts of $10,000 to $49,999",4,Equally male-/female-owned,1,All firms,13.408581,11.052793,14.282453
20,121194,1,All firms,1,All firms,72423,1,00,Total for all sectors,1578601,...,5361848,522,"Firms with sales/receipts of $50,000 to $99,999",4,Equally male-/female-owned,1,All firms,14.272050,11.705148,15.494819
21,410993,1,All firms,1,All firms,167436,1,00,Total for all sectors,7374435,...,28238732,523,"Firms with sales/receipts of $100,000 to $249,999",4,Equally male-/female-owned,1,All firms,15.813530,12.926331,17.156205
22,699613,1,All firms,1,All firms,158634,1,00,Total for all sectors,14927305,...,57285671,525,"Firms with sales/receipts of $250,000 to $499,999",4,Equally male-/female-owned,1,All firms,16.518703,13.458283,17.863561
23,997093,1,All firms,1,All firms,132885,1,00,Total for all sectors,24530387,...,94195158,531,"Firms with sales/receipts of $500,000 to $999,999",4,Equally male-/female-owned,1,All firms,17.015423,13.812599,18.360879
24,4385259,1,All firms,1,All firms,174636,1,00,Total for all sectors,155951280,...,804331935,532,"Firms with sales/receipts of $1,000,000 or more",4,Equally male-/female-owned,1,All firms,18.865054,15.293759,20.505523
25,0,611,Firms with no employees,1,All firms,79850,1,00,Total for all sectors,2950407,...,22932237,1,All firms,4,Equally male-/female-owned,1,All firms,14.897454,-inf,16.948054
26,819768,612,Firms with 1 to 4 employees,1,All firms,392645,1,00,Total for all sectors,24589029,...,147297007,1,All firms,4,Equally male-/female-owned,1,All firms,17.017811,13.616777,18.807962
27,964323,620,Firms with 5 to 9 employees,1,All firms,147179,1,00,Total for all sectors,28508190,...,139224827,1,All firms,4,Equally male-/female-owned,1,All firms,17.165702,13.779182,18.751601
28,115129295,1,All firms,1,All firms,5437782,1,00,Total for all sectors,5640982990,...,33036935112,1,All firms,1,All firms,1,All firms,22.453324,18.561566,24.220892
29,2502804,1,All firms,1,All firms,481981,1,00,Total for all sectors,79672475,...,438363205,1,All firms,1,All firms,1,All firms,18.193435,14.732922,19.898558
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15026,5955,1,All firms,1,All firms,2476,1,99,Industries not classified,53873,...,0,1,All firms,1,All firms,1,All firms,10.894385,8.691986,-inf
15027,1873,1,All firms,1,All firms,1021,1,99,Industries not classified,28124,...,0,1,All firms,1,All firms,1,All firms,10.244379,7.535297,-inf
15028,5866,1,All firms,1,All firms,3293,1,99,Industries not classified,77466,...,0,1,All firms,1,All firms,1,All firms,11.257594,8.676928,-inf
15029,42468,1,All firms,1,All firms,13688,1,99,Industries not classified,599888,...,0,1,All firms,1,All firms,1,All firms,13.304498,10.656506,-inf
15031,4894,1,All firms,1,All firms,2365,1,99,Industries not classified,102335,...,0,1,All firms,1,All firms,2,Veteran-owned,11.536007,8.495765,-inf
15032,6157,1,All firms,1,All firms,2108,1,99,Industries not classified,65148,...,0,1,All firms,1,All firms,3,Equally veteran-/nonveteran-owned,11.084417,8.725345,-inf
15033,55135,1,All firms,1,All firms,23472,1,99,Industries not classified,784492,...,0,1,All firms,1,All firms,4,Nonveteran-owned,13.572792,10.917540,-inf
15036,65491,1,All firms,29,Non-Hispanic,27493,1,99,Industries not classified,938444,...,0,1,All firms,1,All firms,1,All firms,13.751978,11.089668,-inf
15037,1884,1,All firms,1,All firms,2038,1,99,Industries not classified,1603,...,0,510,"Firms with sales/receipts of less than $10,000",1,All firms,1,All firms,7.379632,7.541152,-inf
15038,7850,1,All firms,1,All firms,7418,1,99,Industries not classified,29101,...,0,520,"Firms with sales/receipts of $10,000 to $49,999",1,All firms,1,All firms,10.278528,8.968269,-inf
15039,6092,1,All firms,1,All firms,4450,1,99,Industries not classified,49722,...,0,522,"Firms with sales/receipts of $50,000 to $99,999",1,All firms,1,All firms,10.814203,8.714732,-inf
15040,13981,1,All firms,1,All firms,7741,1,99,Industries not classified,191648,...,0,523,"Firms with sales/receipts of $100,000 to $249,999",1,All firms,1,All firms,12.163416,9.545455,-inf
15041,13955,1,All firms,1,All firms,3710,1,99,Industries not classified,200451,...,0,525,"Firms with sales/receipts of $250,000 to $499,999",1,All firms,1,All firms,12.208325,9.543593,-inf
15042,10217,1,All firms,1,All firms,1639,1,99,Industries not classified,175832,...,0,531,"Firms with sales/receipts of $500,000 to $999,999",1,All firms,1,All firms,12.077284,9.231808,-inf
15043,12208,1,All firms,1,All firms,950,1,99,Industries not classified,303619,...,0,532,"Firms with sales/receipts of $1,000,000 or more",1,All firms,1,All firms,12.623529,9.409847,-inf
15044,0,611,Firms with no employees,1,All firms,3807,1,99,Industries not classified,85528,...,0,1,All firms,1,All firms,1,All firms,11.356599,-inf,-inf
15045,32747,612,Firms with 1 to 4 employees,1,All firms,21303,1,99,Industries not classified,481412,...,0,1,All firms,1,All firms,1,All firms,13.084479,10.396567,-inf
15046,11219,620,Firms with 5 to 9 employees,1,All firms,1733,1,99,Industries not classified,169136,...,0,1,All firms,1,All firms,1,All firms,12.038458,9.325364,-inf
15047,11721,630,Firms with 10 to 19 employees,1,All firms,899,1,99,Industries not classified,179328,...,0,1,All firms,1,All firms,1,All firms,12.096972,9.369137,-inf
15053,7751,1,All firms,1,All firms,3460,1,99,Industries not classified,113889,...,0,1,All firms,2,Female-owned,1,All firms,11.642980,8.955577,-inf
15054,27379,1,All firms,1,All firms,12455,1,99,Industries not classified,458054,...,0,1,All firms,3,Male-owned,1,All firms,13.034742,10.217532,-inf
15055,31056,1,All firms,1,All firms,12030,1,99,Industries not classified,380032,...,0,1,All firms,4,Equally male-/female-owned,1,All firms,12.848011,10.343547,-inf
15056,379,1,All firms,1,All firms,254,1,99,Industries not classified,6915,...,0,1,All firms,1,All firms,1,All firms,8.841448,5.937536,-inf
15068,379,1,All firms,29,Non-Hispanic,254,1,99,Industries not classified,6915,...,0,1,All firms,1,All firms,1,All firms,8.841448,5.937536,-inf
15070,25,1,All firms,1,All firms,26,1,99,Industries not classified,117,...,0,520,"Firms with sales/receipts of $10,000 to $49,999",1,All firms,1,All firms,4.762174,3.218876,-inf
15077,379,612,Firms with 1 to 4 employees,1,All firms,250,1,99,Industries not classified,6851,...,0,1,All firms,1,All firms,1,All firms,8.832150,5.937536,-inf
15085,304,1,All firms,1,All firms,173,1,99,Industries not classified,3829,...,0,1,All firms,2,Female-owned,1,All firms,8.250359,5.717028,-inf
15091,11753,630,Firms with 10 to 19 employees,1,All firms,902,1,99,Industries not classified,180677,...,0,1,All firms,1,All firms,1,All firms,12.104466,9.371864,-inf
15107,344,1,All firms,1,All firms,199,1,99,Industries not classified,5597,...,0,523,"Firms with sales/receipts of $100,000 to $249,999",1,All firms,1,All firms,8.629986,5.840642,-inf
15112,592,612,Firms with 1 to 4 employees,1,All firms,394,1,99,Industries not classified,9813,...,0,1,All firms,1,All firms,1,All firms,9.191463,6.383507,-inf

#### Findings & Application

#### Limitations

#### Next Steps